export interface Trainer {
  id: string;
  userName: string;
  lastName: string;
  firstName: string;
  isActive: boolean;
  specialization: string;
  dob?: string;
  address?: string;
  students: string[];
  trainings: string[];
}

export const trainersData: Trainer[] = [
  {
    firstName: "Eddard",
    lastName: "Stark",
    dob: "",
    address: "",
    specialization: "UI/UX Design",
    students: ["29833a19-e909-4e5c-97ff-2ceee8bd476e"],
    trainings: ["001"],
    id: "3c372c23-3c3b-4bcd-9320-9b03f63ab3e3",
    userName: "ned-stark",
    isActive: true,
  },
  {
    id: "001",
    userName: "trainer1",
    lastName: "Johnson",
    firstName: "Michael",
    dob: "1985-05-20",
    address: "789 Elm St",
    specialization: "JavaScript",
    isActive: true,
    students: ["003", "005", "002"],
    trainings: ["003", "004"],
  },
  {
    id: "002",
    userName: "trainer2",
    lastName: "Anderson",
    firstName: "Laura",
    dob: "1988-07-10",
    address: "101 Pine St",
    specialization: "PHP",
    isActive: true,
    students: ["002"],
    trainings: ["002"],
  },
  {
    id: "003",
    userName: "trainer3",
    lastName: "Williams",
    firstName: "Jessica",
    dob: "1991-09-15",
    address: "222 Maple St",
    specialization: "React",
    isActive: true,
    students: ["003", "004"],
    trainings: ["001", "005"],
  },
  {
    id: "004",
    userName: "trainer4",
    lastName: "Davis",
    firstName: "Ryan",
    dob: "1987-12-03",
    address: "333 Oak St",
    specialization: "Python",
    isActive: true,
    students: ["005", "006"],
    trainings: ["002", "004"],
  },
  {
    id: "005",
    userName: "trainer5",
    lastName: "Garcia",
    firstName: "Mia",
    dob: "1993-04-18",
    address: "444 Birch St",
    specialization: "Java",
    isActive: true,
    students: ["007", "008"],
    trainings: ["005"],
  },
  {
    id: "006",
    userName: "trainer6",
    lastName: "Martinez",
    firstName: "James",
    dob: "1990-08-11",
    address: "555 Pine St",
    specialization: "C#",
    isActive: true,
    students: ["009", "001", "004"],
    trainings: ["003"],
  },
  {
    id: "007",
    userName: "trainer7",
    lastName: "Clark",
    firstName: "Sophie",
    dob: "1989-06-28",
    address: "666 Elm St",
    specialization: "Ruby",
    isActive: true,
    students: ["001", "002", "007"],
    trainings: ["002"],
  },
  {
    id: "008",
    userName: "trainer8",
    lastName: "Miller",
    firstName: "David",
    dob: "1994-02-14",
    address: "777 Birch St",
    specialization: "Angular",
    isActive: true,
    students: ["003", "004"],
    trainings: ["004"],
  },
  {
    id: "009",
    userName: "trainer9",
    lastName: "Anderson",
    firstName: "Emma",
    dob: "1985-11-22",
    address: "888 Oak St",
    specialization: "Vue.js",
    isActive: true,
    students: ["006"],
    trainings: ["005"],
  },
  {
    id: "010",
    userName: "trainer10",
    lastName: "Johnson",
    firstName: "Daniel",
    dob: "1992-06-15",
    address: "999 Pine St",
    specialization: "Swift",
    isActive: true,
    students: ["007", "008"],
    trainings: ["001", "004"],
  },
];
